services:
  kurento:
    build:
      context: kurento
      dockerfile: Dockerfile
      additional_contexts:
        sources: "../"
  
  rest:
    env_file:
      - .env
    build:
      context: rest
      dockerfile: Dockerfile
      additional_contexts:
        sources: "../"
    ports: 
      - "8080:8080"
    depends_on:
      - kurento

