services:
  kurento:
    build:
      context: kurento
      dockerfile: Dockerfile
      additional_contexts:
        sources: "../"
    network_mode: host
    restart: on-failure
  
  rest:
    env_file:
      - .env
    build:
      context: rest
      dockerfile: Dockerfile
      additional_contexts:
        sources: "../"
    restart: on-failure
    network_mode: host
    depends_on:
      - kurento

